---
- name: Provision minio
  hosts: devices
  gather_facts: true

  pre_tasks:
    - name: Load common pre-tasks
      ansible.builtin.import_tasks: ../../tasks/pre_tasks.yml

  roles:
    - role: minio
