---
reverse_proxies:
  - service: baikal
    host: "rpi-lite-2"
    domain: "baikal.doreeto.com"
  - service: synapse
    host: "rpi-4"
    domain: "chat.doreeto.com"
  - service: minio
    host: "rpi-4"
    domain: "minio.doreeto.com"
