---
ansible_python_interpreter: /usr/bin/python3

# Homebrew — single source of truth for brew_user and prefix
brew_user: erron
brew_prefix: /home/linuxbrew/.linuxbrew

# MinIO config
minio_data_path: /srv/minio/data
minio_port: 9000
minio_console_port: 9001
