---
- name: Stop Synapse service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: stop
  vars:
    service_adapter_name: "{{ synapse_service_name }}"
    service_adapter_user: "{{ ansible_user }}"

- name: Restore Synapse data from restic
  ansible.builtin.include_role:
    name: restic
    tasks_from: restore
  vars:
    restic_snapshot_tag: synapse
    restic_restore_target: /

- name: Start Synapse service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: start
  vars:
    service_adapter_name: "{{ synapse_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
