from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from ansible.inventory.manager import InventoryManager
from ansible.parsing.dataloader import DataLoader
from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

from .hostvars import HostVars
from .registry import AppRegistry, AppRegistryEntry
from .yaml import yaml_mapping


class AnsibleDataStore:
    """Central access point for validated Ansible project data."""

    def __init__(self, root: Path | None = None) -> None:
        self.root = root or Path(__file__).resolve().parents[3]
        self.ansible_dir = self.root / "ansible"
        self.inventory_dir = self.ansible_dir / "inventory"
        self.inventory_file = self.inventory_dir / "hosts.yml"
        self.host_vars_dir = self.inventory_dir / "host_vars"
        self.registry_file = self.ansible_dir / "registry.yml"
        self._registry_cache: AppRegistry | None = None
        self._inventory_hosts_cache: list[str] | None = None

    @classmethod
    def from_inventory_file(cls, inventory_file: Path) -> "AnsibleDataStore":
        """Create an isolated store bound to a specific inventory file."""
        store = cls(root=inventory_file.parents[2])
        store.inventory_file = inventory_file
        store.inventory_dir = inventory_file.parent
        store.host_vars_dir = inventory_file.parent / "host_vars"
        store.clear_cache()
        return store

    def clear_cache(self) -> None:
        """Drop any cached registry data."""
        self._registry_cache = None
        self._inventory_hosts_cache = None

    def load_full_registry(self) -> AppRegistry:
        """Return the full validated registry including global_vars."""
        if self._registry_cache is None:
            data = self._read_yaml_mapping(self.registry_file)
            self._registry_cache = AppRegistry.model_validate(data)
        return self._registry_cache

    def load_app_registry(self) -> dict[str, AppRegistryEntry]:
        """Return the validated app registry keyed by app name."""
        return self.load_full_registry().apps

    def all_apps(self) -> list[str]:
        """Return all registered app names in declared order."""
        return list(self.load_app_registry().keys())

    def containerized_apps(self) -> list[str]:
        """Return apps with a long-running container service."""
        registry = self.load_app_registry()
        return [name for name, entry in registry.items() if entry.service_type == "containerized"]

    def get_app_entry(self, app: str) -> AppRegistryEntry:
        """Return a single validated app registry entry."""
        return self.load_app_registry()[app]

    def inventory_hosts(self) -> list[str]:
        """Return host aliases from the actual Ansible inventory."""
        if self._inventory_hosts_cache is None:
            inventory = InventoryManager(
                loader=DataLoader(),
                sources=[str(self.inventory_file)],
            )
            self._inventory_hosts_cache = sorted(host.name for host in inventory.get_hosts())
        return self._inventory_hosts_cache

    def require_inventory_host(self, hostname: str) -> str:
        """Validate that *hostname* exists in the configured inventory."""
        if hostname not in self.inventory_hosts():
            raise KeyError(
                "Unknown inventory host "
                f"'{hostname}'. Add it to {self.inventory_file} "
                "or set HOST to a known alias."
            )
        return hostname

    def host_vars_path(self, hostname: str) -> Path:
        """Return the inventory path for a host's host_vars file."""
        return self.host_vars_dir / f"{hostname}.yml"

    def read_host_vars_raw(self, hostname: str) -> dict[str, Any]:
        """Read host_vars data for a host from the Ansible inventory."""
        self.require_inventory_host(hostname)
        host_vars_file = self.host_vars_path(hostname)
        if not host_vars_file.exists():
            return {}
        return self._read_yaml_mapping(host_vars_file)

    def read_group_vars(self) -> dict[str, Any]:
        """Return plaintext group_vars/all/vars.yml.

        This file is generated by 'make generate-apps' and gitignored; it may not
        exist on a fresh clone and is skipped if absent rather than raising.
        """
        path = self.ansible_dir / "group_vars" / "all" / "vars.yml"
        if not path.exists():
            return {}
        return self._read_yaml_mapping(path)

    def read_effective_vars(self, hostname: str) -> dict[str, Any]:
        """Return group_vars merged with host_vars; host_vars take precedence."""
        effective = self.read_group_vars()
        effective.update(self.read_host_vars_raw(hostname))
        return effective

    def write_host_vars_raw(self, hostname: str, updates: dict[str, Any]) -> None:
        """Merge and persist host_vars data for a host."""
        self.require_inventory_host(hostname)
        host_vars_file = self.host_vars_path(hostname)
        current = self.read_host_vars_raw(hostname)
        current.update(updates)
        host_vars_file.parent.mkdir(parents=True, exist_ok=True)

        yaml_round_trip = YAML()
        yaml_round_trip.preserve_quotes = True

        if "ansible_become_password" in current:
            value = current["ansible_become_password"]
            if not isinstance(value, DoubleQuotedScalarString):
                current["ansible_become_password"] = DoubleQuotedScalarString(str(value))

        with host_vars_file.open("w", encoding="utf-8") as handle:
            yaml_round_trip.dump(current, handle)

    def host_vars(self, hostname: str) -> HostVars:
        """Return validated inventory host vars for a host alias."""
        self.require_inventory_host(hostname)
        return HostVars.from_inventory(hostname, self.read_host_vars_raw(hostname))

    def role_path(self, app: str) -> Path:
        """Return the repo role path for *app* across apps/ and roles/."""
        for base in ("apps", "roles"):
            path = self.ansible_dir / base / app
            if path.exists():
                return path
        raise KeyError(f"No role found for '{app}' under ansible/apps/ or ansible/roles/")

    def add_inventory_host(self, name: str, group: str = "devices") -> None:
        """Add a host entry to the YAML inventory under the specified group."""
        ryaml = YAML()
        ryaml.preserve_quotes = True
        data = ryaml.load(self.inventory_file.read_text(encoding="utf-8"))
        try:
            hosts = data["all"]["children"][group]["hosts"]
        except KeyError:
            raise KeyError(
                f"Inventory group '{group}' not found in {self.inventory_file}"
            ) from None
        if name in hosts:
            raise ValueError(f"Host '{name}' already exists in inventory group '{group}'")
        hosts[name] = None
        with self.inventory_file.open("w", encoding="utf-8") as fh:
            ryaml.dump(data, fh)
        self.clear_cache()

    def remove_inventory_host(self, name: str) -> None:
        """Remove a host entry from all groups in the YAML inventory."""
        ryaml = YAML()
        ryaml.preserve_quotes = True
        data = ryaml.load(self.inventory_file.read_text(encoding="utf-8"))
        removed = False
        for group_data in (data.get("all") or {}).get("children", {}).values():
            if group_data and name in (group_data.get("hosts") or {}):
                del group_data["hosts"][name]
                removed = True
        if not removed:
            raise KeyError(f"Host '{name}' not found in {self.inventory_file}")
        with self.inventory_file.open("w", encoding="utf-8") as fh:
            ryaml.dump(data, fh)
        self.clear_cache()

    def remove_host_vars(self, name: str) -> None:
        """Delete the host_vars file for a host if it exists."""
        self.host_vars_path(name).unlink(missing_ok=True)

    def _read_yaml_mapping(self, source: Path) -> dict[str, Any]:
        """Load a YAML mapping from disk and type it at the boundary."""
        return yaml_mapping(yaml.safe_load(source.read_text(encoding="utf-8")), source=source)


ANSIBLE_DATA = AnsibleDataStore()
