ansible_connection: local
ansible_user: owen
ansible_become_password: "{{ (become_passwords | default({})).get(inventory_hostname, '') }}"
postgres_data_path: /home/linux-hi/postgres
caddy_data_path: /home/linux-hi/caddy
caddy_acme_email: admin@doreeto.com
caddy_routes:
  - host: synapse
    external: chat.doreeto.com
    internal: localhost:8008
