ansible_connection: local
ansible_user: owen
ansible_become_password: "{{ (become_passwords | default({})).get(inventory_hostname, '') }}"
postgres_data_path: /home/linux-hi/postgres
mautrix_whatsapp_data_path: /home/linux-hi/mautrix-whatsapp
mautrix_whatsapp_homeserver_domain: chat.doreeto.com
synapse_data_path: /home/linux-hi/synapse
synapse_server_name: chat.doreeto.com
