ansible_host: 192.168.0.33
ansible_user: avid-askew-dean
ansible_port: 22
ansible_ssh_private_key_file: config/.ed25519
ansible_python_interpreter: /usr/bin/python3
ansible_become_password: "{{ (become_passwords | default({})).get(inventory_hostname, '') }}"
synapse_server_name: chat.doreeto.com
caddy_acme_email: retouch-cork-chunk@duck.com
minio_data_path: /mnt/external/minio
baikal_config_path: /home/linux-hi/baikal/config
baikal_data_path: /home/linux-hi/baikal/data
caddy_routes:
  - host: synapse
    external: chat.doreeto.com
    internal: localhost:8008
  - host: minio
    external: db.doreeto.com
    internal: localhost:9000
postgres_data_path: /home/linux-hi/postgres
jellyfin_media_remote: "pcloud:Media Archive"
