---
- name: Restart postgres
  listen: restart postgres
  ansible.builtin.include_tasks: ../../../roles/service_adapter/tasks/restart.yml
  vars:
    svc_name: "{{ postgres_service_name }}"
    svc_user: "{{ ansible_user }}"
    svc_run_script: "{{ app_user_home }}/bin/run-postgres.sh"
