---
- name: Get UID of {{ service_adapter_user }}
  ansible.builtin.command: "id -u {{ service_adapter_user }}"
  register: _service_adapter_start_uid
  changed_when: false

- name: Start via systemd {{ service_adapter_name }}
  ansible.builtin.systemd:
    name: "{{ service_adapter_name }}"
    scope: user
    state: started
  become: true
  become_user: "{{ service_adapter_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ _service_adapter_start_uid.stdout | trim }}"
  when: service_adapter_backend == 'systemd'
