---
- name: Deregister service (systemd)
  ansible.builtin.include_tasks: teardown_systemd.yml
  when: service_adapter_backend == 'systemd'

- name: Deregister service (cron)
  ansible.builtin.include_tasks: teardown_cron.yml
  when: service_adapter_backend == 'cron'

- name: Deregister service (manual)
  ansible.builtin.include_tasks: teardown_manual.yml
  when: service_adapter_backend == 'manual'
