---
- name: Get UID of {{ service_adapter_user }}
  ansible.builtin.command: "id -u {{ service_adapter_user }}"
  register: _service_adapter_user_uid_out
  changed_when: false

- name: Set _service_adapter_user_uid fact
  ansible.builtin.set_fact:
    _service_adapter_user_uid: "{{ _service_adapter_user_uid_out.stdout }}"

- name: Stop and disable service {{ service_adapter_name }}
  ansible.builtin.systemd:
    name: "{{ service_adapter_name }}"
    scope: user
    state: stopped
    enabled: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ _service_adapter_user_uid }}"
  failed_when: false

- name: Remove Podman quadlet for {{ service_adapter_name }}
  ansible.builtin.file:
    path: "{{ app_user_home }}/.config/containers/systemd/{{ service_adapter_name }}.container"
    state: absent
  become: true

- name: Reload systemd user daemon after removing quadlet for {{ service_adapter_name }}
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ _service_adapter_user_uid }}"
