---
- name: Remove @reboot cron entry for {{ service_adapter_name }}
  ansible.builtin.cron:
    name: "{{ service_adapter_name }}-start"
    cron_file: "{{ service_adapter_name }}"
    user: "{{ service_adapter_user }}"
    state: absent
  become: true

- name: Remove run script for {{ service_adapter_name }}
  ansible.builtin.file:
    path: "{{ service_adapter_run_script }}"
    state: absent
  become: true
