---
- name: Stop Baikal service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: stop
  vars:
    service_adapter_name: "{{ baikal_service_name }}"
    service_adapter_user: "{{ ansible_user }}"

- name: Restore Baikal config and data from restic
  ansible.builtin.include_role:
    name: restic
    tasks_from: restore
  vars:
    restic_snapshot_tag: baikal
    restic_restore_target: /

- name: Start Baikal service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: start
  vars:
    service_adapter_name: "{{ baikal_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
