[raspberry_pi]
rpi ansible_host=192.168.0.33
# rpi2 ansible_host=192.168.0.34   # add more Pis here; use HOST=rpi2 make site

[raspberry_pi:vars]
ansible_user=erron
ansible_port=22
ansible_ssh_private_key_file=config/.ed25519
