---
baikal_config_path: /home/linux-hi/baikal/config
baikal_data_path: /home/linux-hi/baikal/data

baikal_configured_version: "0.10.1"
baikal_timezone: Europe/Paris
baikal_card_enabled: true
baikal_cal_enabled: true
baikal_dav_auth_type: Digest
baikal_failed_access_message: "user %u authentication failure for Baikal"
baikal_auth_realm: BaikalDAV
baikal_base_uri: ""
baikal_invite_from: noreply@localhost

baikal_db_backend: pgsql
baikal_db_host: host.containers.internal
baikal_db_name: baikal
baikal_db_user: baikal

# SQLite fallback — override baikal_db_backend to 'sqlite' in host_vars to use this
baikal_db_sqlite_path: "{{ baikal_data_path }}/db/db.sqlite"
