---
- name: Provision base dependencies
  hosts: devices
  gather_facts: true

  pre_tasks:
    - name: Load common pre-tasks
      ansible.builtin.import_tasks: ../tasks/pre_tasks.yml

  roles:
    - role: auto-updates
      tags: [base]
      become: true

    - role: podman
      tags: [podman]
      become: true

    - role: rclone
      tags: [base]

    - role: caddy
      tags: [caddy]
      become: true
