---
- name: Restart mautrix-whatsapp
  listen: restart mautrix-whatsapp
  ansible.builtin.include_tasks: ../../../roles/service_adapter/tasks/restart.yml
  vars:
    service_adapter_name: "{{ mautrix_whatsapp_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
    service_adapter_run_script: "{{ app_user_home }}/bin/run-mautrix-whatsapp.sh"
