---
- name: Import postgres playbook
  import_playbook: ../postgres/playbook.yml

- name: Import caddy playbook
  import_playbook: ../caddy/playbook.yml

- name: Provision baikal
  hosts: devices
  gather_facts: true

  pre_tasks:
    - name: Load common pre-tasks
      ansible.builtin.import_tasks: ../../tasks/pre_tasks.yml

  roles:
    - role: baikal
