---
- name: restart baikal
  ansible.builtin.systemd:
    name: baikal
    scope: user
    state: restarted
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ _app_user_uid }}"
