---
- name: restart baikal
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: restart
  vars:
    svc_name: "{{ baikal_service_name }}"
    svc_user: "{{ ansible_user }}"
    svc_run_script: "{{ app_user_home }}/bin/run-baikal.sh"
