---
- name: Provision Raspberry Pi
  hosts: raspberry_pi
  gather_facts: true

  roles:
    - role: auto-updates
      tags: [base]
      become: true

    - role: homebrew
      tags: [homebrew]

    - role: podman
      tags: [podman]
      become: true

    - role: rclone
      tags: [rclone]
      become: true

    - role: storage
      tags: [storage]
      become: true

    - role: jellyfin
      tags: [jellyfin]
      become: true

    - role: minio
      tags: [minio]
