---
- name: Restart minio
  listen: restart minio
  ansible.builtin.include_tasks: ../../../roles/service_adapter/tasks/restart.yml
  vars:
    service_adapter_name: "{{ minio_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
    service_adapter_run_script: "{{ app_user_home }}/bin/run-minio.sh"
