---
- name: Restart minio
  listen: restart minio
  ansible.builtin.include_tasks: ../../../roles/service_adapter/tasks/restart.yml
  vars:
    svc_name: "{{ minio_service_name }}"
    svc_user: "{{ ansible_user }}"
    svc_run_script: "{{ app_user_home }}/bin/run-minio.sh"
