---
- name: Stop mautrix-whatsapp service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: stop
  vars:
    service_adapter_name: "{{ mautrix_whatsapp_service_name }}"
    service_adapter_user: "{{ ansible_user }}"

- name: Restore mautrix-whatsapp data from restic
  ansible.builtin.include_role:
    name: restic
    tasks_from: restore
  vars:
    restic_snapshot_tag: mautrix-whatsapp
    restic_restore_target: /

- name: Start mautrix-whatsapp service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: start
  vars:
    service_adapter_name: "{{ mautrix_whatsapp_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
