---
- name: Restart postgres
  listen: restart postgres
  ansible.builtin.include_tasks: ../../../system/service_adapter/tasks/restart.yml
  vars:
    service_adapter_name: "{{ postgres_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
    service_adapter_run_script: "{{ app_user_home }}/bin/run-postgres.sh"
