"""Generate ansible/group_vars/all/vars.yml from ansible/registry.yml."""

from __future__ import annotations

from linux_hi.models import ANSIBLE_DATA
from linux_hi.models.ansible.registry import AppRegistry, AppRegistryEntry

_GENERATED_HEADER = (
    "# Generated by 'make generate-apps' — do not edit.\n"
    "# Source of truth: ansible/registry.yml\n"
    "---\n"
)


def _var_prefix(app: str) -> str:
    return app.replace("-", "_")


def _service_var_lines(prefix: str, entry: AppRegistryEntry) -> list[str]:
    """Return YAML lines for the service identity vars derivable from the registry."""
    lines = []
    if entry.service_name is not None:
        lines.append(f"{prefix}_service_name: {entry.service_name}")
    if entry.image is not None:
        lines.append(f"{prefix}_image: {entry.image}")
    if entry.port is not None:
        lines.append(f"{prefix}_port: {entry.port}")
    return lines


def _render_group_vars(full_registry: AppRegistry) -> str:
    lines: list[str] = [_GENERATED_HEADER]
    if full_registry.global_vars:
        for key, value in full_registry.global_vars.items():
            lines.append(f'{key}: "{value}"')
        lines.append("")
    for app, entry in full_registry.apps.items():
        prefix = _var_prefix(app)
        app_lines = [
            *_service_var_lines(prefix, entry),
            *(f"{k}: {v}" for k, v in entry.shared_vars.items()),
        ]
        if entry.runtime_uid is not None:
            app_lines.append(f"{prefix}_runtime_uid: {entry.runtime_uid}")
        if entry.runtime_gid is not None:
            app_lines.append(f"{prefix}_runtime_gid: {entry.runtime_gid}")
        if app_lines:
            lines.append(f"# {app}")
            lines.extend(app_lines)
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    full_registry = ANSIBLE_DATA.load_full_registry()

    group_vars_path = ANSIBLE_DATA.ansible_dir / "group_vars" / "all" / "vars.yml"
    group_vars_path.write_text(_render_group_vars(full_registry), encoding="utf-8")

    print(f"  [OK  ]  Regenerated {group_vars_path.relative_to(ANSIBLE_DATA.ansible_dir.parent)}")


if __name__ == "__main__":
    main()
