"""Unit tests for generate-apps CLI helpers."""

from __future__ import annotations

from pathlib import Path

import pytest

from linux_hi.cli import generate_apps
from linux_hi.models.ansible.registry import AppRegistry, AppRegistryEntry


def test_var_prefix_replaces_dashes() -> None:
    """Var prefix helper should convert app names to underscore-safe prefixes."""
    assert generate_apps._var_prefix("mautrix-whatsapp") == "mautrix_whatsapp"


def test_service_var_lines_include_only_present_fields() -> None:
    """Service variable renderer should emit only non-null service fields."""
    entry = AppRegistryEntry(
        service_type="containerized",
        service_name="svc",
        image="example:1",
        port=8008,
    )

    lines = generate_apps._service_var_lines("app", entry)

    assert lines == ["app_service_name: svc", "app_image: example:1", "app_port: 8008"]


def test_render_group_vars_includes_header_globals_and_app_sections() -> None:
    """Group vars renderer should include generated header, globals, and app-scoped vars."""
    registry = AppRegistry(
        global_vars={"postgres_host_access_name": "host.containers.internal"},
        apps={
            "synapse": AppRegistryEntry(
                service_type="containerized",
                service_name="synapse",
                image="ghcr.io/element-hq/synapse:v1.151.0",
                port=8008,
                runtime_uid=991,
                runtime_gid=991,
                shared_vars={"synapse_server_name": "chat.example.com"},
            )
        },
    )

    text = generate_apps._render_group_vars(registry)

    assert "Generated by 'make generate-apps'" in text
    assert 'postgres_host_access_name: "host.containers.internal"' in text
    assert "# synapse" in text
    assert "synapse_service_name: synapse" in text
    assert "synapse_image: ghcr.io/element-hq/synapse:v1.151.0" in text
    assert "synapse_port: 8008" in text
    assert "synapse_runtime_uid: 991" in text
    assert "synapse_runtime_gid: 991" in text


def test_main_writes_vars_file(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Main should render registry content to ansible/group_vars/all/vars.yml."""
    ansible_dir = tmp_path / "ansible"
    vars_dir = ansible_dir / "group_vars" / "all"
    vars_dir.mkdir(parents=True, exist_ok=True)

    registry = AppRegistry(
        global_vars={"k": "v"},
        apps={"app": AppRegistryEntry(service_type="containerized", service_name="app")},
    )

    class _Store:
        def __init__(self) -> None:
            self.ansible_dir = ansible_dir

        def load_full_registry(self) -> AppRegistry:
            return registry

    monkeypatch.setattr(generate_apps, "ANSIBLE_DATA", _Store())

    generate_apps.main()

    output = (vars_dir / "vars.yml").read_text(encoding="utf-8")
    assert 'k: "v"' in output
    assert "app_service_name: app" in output
