var_hints:
  minio_data_path:
    hint: "persistent path for MinIO data"
    default: /home/raspberry-hi/minio

vault_secrets:
  - key: minio_root_user
    label: MinIO root username
    hidden: false
  - key: minio_root_password
    label: MinIO root password
    hidden: true
