var_hints:
  minio_data_path: "persistent path for MinIO data"

vault_secrets:
  - key: minio_root_user
    label: MinIO root username
    hidden: false
  - key: minio_root_password
    label: MinIO root password
    hidden: true
