---
- name: Stop MinIO service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: stop
  vars:
    service_adapter_name: "{{ minio_service_name }}"
    service_adapter_user: "{{ ansible_user }}"

- name: Restore MinIO data from restic
  ansible.builtin.include_role:
    name: restic
    tasks_from: restore
  vars:
    restic_snapshot_tag: minio
    restic_restore_target: /

- name: Start MinIO service
  ansible.builtin.include_role:
    name: service_adapter
    tasks_from: start
  vars:
    service_adapter_name: "{{ minio_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
