---
- name: Restart baikal
  listen: restart baikal
  ansible.builtin.include_tasks: ../../service_adapter/tasks/restart.yml
  vars:
    service_adapter_name: "{{ baikal_service_name }}"
    service_adapter_user: "{{ ansible_user }}"
    service_adapter_run_script: "{{ app_user_home }}/bin/run-baikal.sh"
